# Generated by Django 5.0.6 on 2024-06-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id_tier', models.AutoField(db_column='idTier', primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(blank='false', max_length=100, null='true', unique=True)),
                ('password', models.CharField(blank='true', max_length=30, null='true')),
                ('activo', models.IntegerField()),
                ('id_tier', models.ForeignKey(db_column='IDTier', on_delete=django.db.models.deletion.CASCADE, to='rum.tier')),
            ],
        ),
    ]
