# Generated by Django 5.0.6 on 2024-06-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
